[build]
  command = "cd beezTop && hugo --gc --minify -D -b $URL"
  publish = "beezTop/public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "America/New_York"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
HUGO_VERSION = "0.112.7"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd beezTop && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.112.7"

[context.branch-deploy]
command = "cd beezTop && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.112.7"
